/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class security_BoilerManagerWithoutValidation */

#ifndef _Included_security_BoilerManagerWithoutValidation
#define _Included_security_BoilerManagerWithoutValidation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     security_BoilerManagerWithoutValidation
 * Method:    setTemperature
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_security_BoilerManagerWithoutValidation_setTemperature
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
