/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class security_BoilerManagerWithValidation */

#ifndef _Included_security_BoilerManagerWithValidation
#define _Included_security_BoilerManagerWithValidation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     security_BoilerManagerWithValidation
 * Method:    setTemperature
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_security_BoilerManagerWithValidation_setTemperature
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
